---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
```
```{r}
fda_drugs <- read_csv('Data/FDA_df2.csv')
```
```{r}
conditions_drugs <- read_csv('Data/fullconditions2.csv')
```

```{r}
side_effects <- read_csv('Data/SE_df_update2.csv')
```

```{r}
food <- read_csv('Data/food_data_update.csv')
```
```{r}
skin_breakdown_food <- read_csv('Data/skin_break_food.csv')
```

```{r}
fall_risk_food <- read_csv('Data/fall_foods.csv')
```

```{r}
side_effects<- side_effects %>%
  select(-c(`Unnamed: 0`, `...1`))
  
```


```{r}
side_effects %>%
  #filter(medical_attention == 'Side effects requiring immediate medical attention') %>%
  filter(Side_effect != 'NA') %>%
  group_by(Side_effect) %>%
  summarize(number = n()) %>%
  arrange(desc(number)) %>%
  head(20) %>%
  ggplot(aes(x = reorder(Side_effect, number), y = number)) +
  geom_col() +
  coord_flip()
```

```{r}
side_effects %>%
  filter(Side_effect != 'NA', webscraping_name == 'gabapentin') %>%
  group_by(medical_attention) %>%
  summarize(number = n())%>%
        ggplot(aes(x = medical_attention, y = number)) +
        geom_col()
```
```{r}
side_effects %>%
  group_by(Risk_factor) %>%
  summarize(n())
```
```{r}
food %>%
  filter(str_detect(description, 'soup')|str_detect(description,'applesauce')|str_detect(description,'yogurt'))
  
```
```{r}
food %>%
  filter(name == 'Protein') %>%
  arrange(desc(amount))
```

```{r}
skin_breakdown_food <- skin_breakdown_food %>%
  select(-c(...1,AVG)) 
```

```{r}
colnames(skin_breakdown_food)
```
```{r}
side_effects$Risk_factor[side_effects$Risk_factor == 'nan'] <- 'None'
```

```{r}
skin_breakdown_food %>%
  filter(SUM > 0)
```
```{r}
length(unique(side_effects$webscraping_name))
```

```{r}
length(unique(conditions_drugs$Condition))
```
```{r}
pregnancy_symbols <-  c("A","B","C","D","X","N")
pregnancy_meanings <- c("Adequate and well-controlled studies have failed to demonstrate a risk to the fetus in the first trimester of pregnancy (and there is no evidence of risk in later trimesters)",
                           "Animal reproduction studies have failed to demonstrate a risk to the fetus and there are no adequate and well-controlled studies in pregnant women.",
                           "Animal reproduction studies have shown an adverse effect on the fetus and there are no adequate and well-controlled studies in humans, but potential benefits may warrant use in pregnant women despite potential risks.",
                           "There is positive evidence of human fetal risk based on adverse reaction data from investigational or marketing experience or studies in humans, but potential benefits may warrant use in pregnant women despite potential risks.",
                           "Studies in animals or humans have demonstrated fetal abnormalities and/or there is positive evidence of human fetal risk based on adverse reaction data from investigational or marketing experience, and the risks involved in use in pregnant women clearly outweigh potential benefits.",
                           "FDA has not classified the drug.")
```

```{r}
preg_symbols <- tibble(Symbol = pregnancy_symbols, Definition = pregnancy_meanings)
```

